version: 2.1
jobs:
  build:
    working_directory: ~/algotrade
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run:
          command: |
            sudo apt install pipenv
            pipenv install -r requirements
workflows:
  build-and-test:
    jobs:
      - build