version: 2.1
jobs:
  build:
    working_directory: ~/algotrade
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: pipenv install -r requirements
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run: pipenv run python test.py
workflows:
  build-and-test:
    jobs:
      - build